apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webfrontend
spec:
  template:
    metadata:
      labels:
        app: webfrontend
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: webfound
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        tty: true
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webfrontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: webfrontend
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webfrontend
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: webfrontend.47cab6a688394292b0b9.eastus.aksapp.io
    http:
      paths:
      - backend:
          serviceName: webfound
          servicePort: 80
        path: /
